### ISSUE TITLE
Needs a "Can't find .env" warning dialog

### ISSUE THREAD

**Issue by sgehrman** [EOSIO/ual-reactjs-renderer#65]
Thought this was completely broken.  I edited the default.env, but didn't see the readme about renaming it to .env.  Would save some time if at least you console.log('No env found').

**Comment by chris-allnutt** [comment]
@sgehrman I'd recommend something before we load env variables and console errors if a setting is missing.

**Comment by GreenBusDriver** [comment]
Fixed in PR #76
